### ISSUE TITLE
All runners could be sync and async to optimize resources

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#165]
Share same pool of runners for sync and async. 

So I was thinking about how this could work on a single binary/machine (instead of separate runners), and had this idea:

* a request comes in
* if sync, put in sync channel - implemented (partially?) here #92 
* if async, put in message queue

Then we just have a single go routine that does the following:

* read off channel, if task exists, fire up go routine to execute it, write the results to the HTTP response. If no sync tasks:
* read off message queue, if task exists, fire up go routine to execute it (probably nearly the exact same way as above, except we don't write any results

Or maybe those are two go routines, but the second one pauses until resources are available.

Prior convo here: https://github.com/iron-io/functions/issues/104#issuecomment-248947222 for details.

**Comment by ccirello** [comment]
Done in #314

**Comment by treeder** [comment]
I'm pretty sure this isn't done. Async is still totally separate from sync from what I can tell.

**Comment by ccirello** [comment]
How sure are you sure? Because I am pretty confident that I have unified sync and async jobs to use the same workers.

**Comment by ccirello** [comment]
Check https://github.com/iron-io/functions/blob/master/api/runner/async_runner.go#L130 -- as you can see, it talks to `tasks` channel - which is the same channel that takes in sync tasks. So they _were_ separated stuff, not anymore. Moving convo to slack.

**Comment by treeder** [comment]
Ok, thanks for link.
