### ISSUE TITLE
Remove error in logs when image not found

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#182]
This is in runner I believe. 

<img width="759" alt="screen shot 2016-10-18 at 4 07 24 pm" src="https://cloud.githubusercontent.com/assets/75826/19499773/162409e2-954d-11e6-8d73-b7a6c14a27ce.png">

Change it to info, and only error if the image can't be pulled.

**Comment by treeder** [comment]
I believe this is fixed now? I don't think it shows up anymore.

**Comment by ccirello** [comment]
I think so.
