### ISSUE TITLE
Update iron/node image

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#284]
It's pretty old now: https://github.com/iron-io/dockers/tree/master/node

And maybe some of the other images in there as well. Perhaps make a top level rebuild all images script that builds and pushes everything.

**Comment by ccirello** [comment]
This is more adequate to iron-io/dockers repo. Opening there. Closing here.

**Comment by ccirello** [comment]
https://github.com/iron-io/dockers/issues/56
