### ISSUE TITLE
fnctl: Add python support

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#310]
https://github.com/iron-io/dockerworker

**Comment by ccirello** [comment]
The dockerworker example is already there.

#328 fixes the `fn init`.

**Comment by jotes** [comment]
It looks like iron.io supports only python2... would you be interested in support for python3? I could help with that.

**Comment by seiflotfy** [comment]
@jotes that would be great. I can meet you on the slack channels and we do it together :)
