### ISSUE TITLE
Unable to run sync route execution longer than 60 seconds

### ISSUE THREAD

**Issue by denismakogon** [iron-io/functions#339]
Container unexpectedly dies during sync execution but runs fine in docker using command after 1 minute execution:

`docker run -d -i -P denismakogon/aioservice-examples:latest`

Images: 

- [denismakogon/aioservice-examples:latest](https://hub.docker.com/r/denismakogon/aioservice-examples/tags/)
- [denismakogon/sleep120:latest](https://hub.docker.com/r/denismakogon/sleep120/)

Steps to reproduce:

`
curl -X POST -d '{"app":{"name":"testapp"}}' localhost:8080/v1/apps
`

`
curl -X POST -d '{"route":{"type": "sync", "path": "/sync", "image": "denismakogon/sleep120"}}' localhost:8080/v1/apps/testapp/routes
`

`
curl -X POST localhost:8080/r/testapp/sync
`

Function logs:
When POST to /r/{app}/route submitted
```
INFO[1442]                                               name=run.testapp.requests type=count value=1
INFO[1442]                                               name=run.testapp.waittime type=time value=0s
```

When container dies
```
INFO[1502] container status                              container_error= container_finished=2016-11-24 09:37:59.410257982 +0000 UTC container_running=false container_status=exited exit_code=137
INFO[1502]                                               name=run.testapp.error type=count value=1
INFO[1502]                                               name=run.testapp.time type=time value=1m0.06911744s
INFO[1502]                                               name="run.exec_time" type=time value=1m0.06911744s
```

But both containers are capable to run on Docker successfully.

It appears that sync func can run no longer than 60 seconds (Docker ReST client default HTTP timeout is 60 seconds).

Functions latest commit: af14904
Go version: 1.7
Docker version: 1.12.3, build 6b644ec

**Comment by ccirello** [comment]
This is a bug. The problem is that there is a hard-coded 30s timeout in the source code.

https://github.com/iron-io/functions/blob/c14bc323f97f4c8d11628b27496903f80dab962e/api/server/runner.go#L172

@treeder @pedronasser @seiflotfy - what would the appropriate fix? Is the timeout an attribute of the route or the task call?

**Comment by denismakogon** [comment]
@ccirello would be the right fix to set execution timeout through API? There are three cases possible:
1. No timeout specified - use default 60 seconds (or whatever it be)
2. Timeout specified - run within timeout
3. Run until not finished

cc @treeder @pedronasser @seiflotfy

**Comment by ccirello** [comment]
> would be the right fix to set execution timeout through API?

I don't see any other place to land the fix. :) It _must_ be in the API - the only you way you can interface with IronFunctions daemon. 

However, is this an attribute of the route (`PUT /v1/apps/{app}/routes/{route}`) or the task (`POST /r/{app}/{route}`)?

**Comment by denismakogon** [comment]
@ccirello as i can see, it should be a part of `routers` API (`POST /v1/apps/{app}/routes/{route}`).

**Comment by pedronasser** [comment]
I think the Timeout should be configured in the route/apps configuration and even maybe via a Header. If no timeout is specified use the default. (like @denismakogon suggested)

**Comment by denismakogon** [comment]
@pedronasser to what kind of headers you're referring to?. We already have `config` object in payload, can't we just check on the API side if timeout was specified or not. In such case we have very small API impact (AFICS, only doc/swagger impact).
