### ISSUE TITLE
Linux distribution packages

### ISSUE THREAD

**Issue by ucirello** [iron-io/functions#347]
I suggest deb and deriveds, rpm and deriveds, arch and alpine.

Targeting LTS's for now.

**Comment by denismakogon** [comment]
So, there's simple tool (https://github.com/Debian/dh-make-golang) to build Go packages for Debian, but it still supports Go 1.6 only. I tried to build code:
```
ubuntu@ubuntu:~$ dh-make-golang github.com/iron-io/functions
2017/03/12 21:20:25 Downloading "github.com/iron-io/functions/..."
go get: 6.82 MiBpackage github.com/iron-io/functions
	imports context: unrecognized import path "context" (import path does not begin with hostname)
go get: 404.57 MiB2017/03/12 21:23:07 Could not create a tarball of the upstream source: exit status 1
```
So, this problem specific for code transition from Go 1.6 to 1.7
Nevertheless, worth tracking project state.
