### ISSUE TITLE
How to use without Dockerhub

### ISSUE THREAD

**Issue by jezell** [iron-io/functions#348]
Can't seem to locate the docs, even the fn tool seems to imply that you need a docker hub username. Seems like you should be able to:

1) Use local images without pulling registry. Kubernetes pods for example have options for specifying imagePullPolicy: Always | IfNotPresent | Never.

2) Use a custom registry

But can't seem to find the docs about enabling either of these.

**Comment by pedronasser** [comment]
This is something we've been discussing for a while.
The first idea is to check first for local images before checking for remote registries.
Then we can move to support a custom registry.
This is in our TODO list.

**Comment by denismakogon** [comment]
@pedronasser Yeah, i also mentioned that if image is available locally, `functions` complaining that image was not found.

**Comment by jezell** [comment]
Seems like a pull policy for the function similar to kubernetes pods would be the best approach to handle this type of thing instead of hard coding behavior. Locally you often never want a registry to be involved since you don't have a registry running and aren't going to be pushing to one. In scenarios where you are pre-pulling or building images locally, you also don't want to run the risk of pulling things from a registry unintentionally when it's not your intention to ever use a registry.

**Comment by treeder** [comment]
@jezell how would you distribute the images to the cluster of functions nodes in a "never pull" scenario?

Or would it just be on you to ensure those images are on every machine before hand?

**Comment by treeder** [comment]
Checklist

* [ ] https://github.com/iron-io/functions/issues/357
* [ ]

**Comment by jezell** [comment]
So for local dev it's very useful because generally you are building the images here. The thinking behind NeverPull in Kubernetes was to handle any sort of scenario that pulling images wasn't directly supported by Jubernetes. For example, let's say a new 3rd party registry comes out with a different API, or the authentication used by your docker registry is custom, NeverPull is designed as a fallback for any scenario where kubernetes doesn't know how to pull the image automatically and leaves the problem of getting the image on the machine to the user.
