### ISSUE TITLE
Improve `fn publish` command

### ISSUE THREAD

**Issue by ccirello** [iron-io/functions#352]
https://github.com/iron-io/functions/pull/351

Most likely `funcfile` struct can be trimmed down to fewer attributes.

**Comment by treeder** [comment]
I think `fn publish` should work something along these lines:

`fn publish APP_NAME`

* Recurse through all subdirectories
* If there is a func.yaml file or a Dockerfile, build the function and push it
* Update route with IronFunctions server. Route path being the `route` defined in the func.yaml file or the directory name. (should `route` be changed to `path` in func.yaml?). App name being APP_NAME.

**Comment by treeder** [comment]
Maybe we should change the name of this command too, since it's really only for bulk deploy.

**Comment by treeder** [comment]
Let's fork this example: https://github.com/bfirsh/serverless-docker-voting-app and get it working with IronFunctions, it's a good example for this exact thing.
