### ISSUE TITLE
app_name in HTTP POST to /apps/{app}/routes ignored

### ISSUE THREAD

**Issue by denismakogon** [iron-io/functions#361]
Assume you have create app with name `testapp` and you want to create a route pinned to it:

`curl -X POST -d '{"route":{"type": "sync", "path": "/hello-sync", "image": "iron/hello", "appname": "testapppp"}}' localhost:8080/v1/apps/testapp/routes`

As response you get:
`{"message":"Route successfully created","route":{"app_name":"testapp","path":"/hello-sync","image":"iron/hello","memory":128,"type":"sync","config":null}}`

But app name in 1st command is wrong.

Solution:
drop appname from HTTP POST request body to `/apps/{app}/routes`

**Comment by pedronasser** [comment]
@denismakogon The route's AppName is defined as the name used in the URL param `:app`.
So yes, the route.AppName in the request body is just ignored.
But also, the correct field for `AppName` is app_name and not `appname`.

**Comment by denismakogon** [comment]
@pedronasser indeed, but problem still there.

**Comment by denismakogon** [comment]
@pedronasser from user perspective misleading redundancy will be confusing, don't you think so?

**Comment by treeder** [comment]
I agree, we should probably remove app_name from any per function things, the app is defined while executing `fn` commands and one function may be used in many apps, doesn't make too much sense to hard code it to a function.

**Comment by treeder** [comment]
Added a follow up issue with checklist to resolve this.
