### ISSUE TITLE
Make ReST API error messages more verbose

### ISSUE THREAD

**Issue by denismakogon** [iron-io/functions#362]
It would be nice to have HTTP error messages more verbose, for instance, if i would submit a route with non-existing execution type (lest say `sync-a`), API will return `Invalid JSON`.
But technically, request body formed correctly, but error in specific field value.
For given case it would be nice to have error message as:

`Invalid route type`

There are multiple places where such improvement may bring better user experience.

**Comment by ccirello** [comment]
In HEAD, this is handled correctly. See the validation message in the example below:
```Shellsession
$ curl -X POST -d '{"route":{"type": "asynca", "path": "/hello-sync2", "image": "iron/hello", "format": "http", "max_concurrency":2 }}' localhost:8080/v1/apps/testapp/routes
{"error":{"message":"validation failure list:\nvalidation failure list:\nInvalid route Type"}}
```
