### ISSUE TITLE
Remove app_name from per function endpoints

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#364]
See #361 for details. Closes #361 

* [x] Remove app_name from the body of this endpoint 
* [x] Remove app_name func.yaml docs: https://github.com/iron-io/functions/blob/master/docs/function-file.md
* [x] Remove app_name flag in `fn`

**Comment by ccirello** [comment]
Check https://github.com/iron-io/functions/pull/359/files for checkbox 2 and 3

**Comment by ccirello** [comment]
Check https://github.com/iron-io/functions/pull/370/files for checkbox 1
