### ISSUE TITLE
Add documentation related to SpecialHandlers

### ISSUE THREAD

**Issue by pedronasser** [iron-io/functions#369]
Add to: https://github.com/iron-io/functions/blob/master/docs/operating/extending.md

**Comment by pedronasser** [comment]
@ccirello @treeder @seiflotfy I'm thinking on an alternative for these SpecialHandlers.
I think there's a better way to handle that.

**Comment by ccirello** [comment]
@pedronasser can we make it for the alpha2 cycle? or should defer to beta1?

**Comment by pedronasser** [comment]
I'll add a documentation for this.
