### ISSUE TITLE
Multiple routines use non-threadsafe cache

### ISSUE THREAD

**Issue by nikhilm** [iron-io/functions#384]
Did I miss something?

https://github.com/iron-io/functions/blob/a7a466f968006a0dc04668b44e4e04da5b942b46/api/server/runner.go#L93 is called from multiple handlers, but is not thread safe https://github.com/iron-io/functions/blob/a7a466f968006a0dc04668b44e4e04da5b942b46/api/server/internal/routecache/lru.go

**Comment by ccirello** [comment]
Could you please double check? I am pretty confident we've have guarded the LRU cache with mutexes. Refer to https://github.com/iron-io/functions/blob/2c56e7975d5ea469384eb6d4dae97c4652bdb459/api/server/server.go#L133

**Comment by nikhilm** [comment]
Guess you are right. Could use some refactoring to move the mutex into the cache. We already have well tested lrucache in some other code. Not urgent.
