### ISSUE TITLE
Check Lambda-imported functions with Hot Containers

### ISSUE THREAD

**Issue by ucirello** [iron-io/functions#386]

**Comment by jconning** [comment]
@ccirello my understanding is that functions that run with Hot Containers need to be written to read from stdin and write to stdout in chunks.  Lambda doesn't have such functionality.  How do you envision that Lambda-imported functions will work with Hot Containers?

**Comment by ccirello** [comment]
The problem with the current implementation seems to be that the libraries we wrote to enable the use of lambda functions with IronFunctions does not know how to handle the permanent I/O stream. They'll need to be modified in a such a way that on the conclusion of its execution it reads from stdin and run the next incoming call.
