### ISSUE TITLE
Start/stop endpoint

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#390]
To tell IronFunctions stop taking async jobs, in order for an external service to gracefully shutdown an IronFunctions node.

**Comment by ccirello** [comment]
I believe this is done already: https://github.com/iron-io/functions/commit/aa12f3c724223f884f1e6e467738c0fbef7ade4f

what are you suggesting as an addition?

**Comment by treeder** [comment]
Is there an endpoint to tell it to stop?
