### ISSUE TITLE
Revisit LRU cache

### ISSUE THREAD

**Issue by ccirello** [iron-io/functions#400]
- [ ] Global single LRU
- [ ] Use Route own information to provide uniqueness within LRU
- [ ] Handle cache invalidation when routes are updated/created

// cc: @treeder

**Comment by treeder** [comment]
Should also have a timeout on the routes too, so we're sure that it gets updated if something changes.

**Comment by seiflotfy** [comment]
@ccirello in reference to the second point. The same route but with different settings should be considered as 2 different routes?

**Comment by ccirello** [comment]
@seiflotfy - all route information: image name and tag, configuration and whatnots.

**Comment by ccirello** [comment]
@seiflotfy do we have a PR for this?

**Comment by treeder** [comment]
Just curious about the comments here, the route key should only contain what we can get from the user request, not everything about the route. Which means basically means the key should just contain the app name and the path.

**Comment by ccirello** [comment]
The PR is restricted to app name and route path.
