### ISSUE TITLE
fnctl: Creating routes ignores the route path and assigns function name

### ISSUE THREAD

**Issue by Gouthamve** [iron-io/functions#413]
### What did I do?
Ran: `fn routes create myapp /hello` inside a function named irn-hello.

### What was expected?
Route is created at path: /hello

### What was observed?
Route is created at path: /irn-hello

**Comment by ccirello** [comment]
hi @Gouthamve - thanks for reporting this. Could you please confirm the installed version you are using? 

```
$ fn --version
```

**Comment by Gouthamve** [comment]
I built it from the latest source: `fn version 0.1.39`
