### ISSUE TITLE
Can't update a route and show better error message

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#421]
I get this response:

```json
{"error":{"message":"Could not create route"}}
```

Which isn't helpful at all. 

And this is in the functions logs:

```
Dec 12 23:01:36 953f0bcf2c83 functions:  time="2016-12-13T07:01:36Z" level=error msg="Could not create route" action="server.handleRouteCreate)-fm" app=tbots error="Route already exists"  
```

Which actually has helpful information, ie: that it already exists. That said, I can't update my route to a new version because of this error.

**Comment by pedronasser** [comment]
Is this bug still valid?
