### ISSUE TITLE
fn tool should support simple updating of a function

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#439]
A typical scenario would be to update/fix a function, then want to deploy it again. The process would be:

```sh
fn bump
fn build
# test function
fn push
fn update route myapp /path <-- does not exist
```

I wasn't able to update the route with the new version after the bump. 

May even make sense to merge one or two of those, for instance:

fn bump -> bump version and build new image (since you'd almost always do a built right after a bump anyways)

fn update route -> push, then update route?  Not sure if this would always be the case, but seems like it might be if you're in a directory with func.yaml (ie: working on a function).

**Comment by ccirello** [comment]
wrt: last two lines ~ it feels non-recursive `fn deploy` all over again.

**Comment by treeder** [comment]
@ccirello this isn't recursive, just deploying a single function. The purpose of this issue is that I wasn't able to update the route with the new version. `fn update route ...` doesn't exist (or didn't when I created this issue). Will have to try again to see if this has been fixed.

**Comment by treeder** [comment]
@pedronasser is thie one done now with your recent changes?

**Comment by treeder** [comment]
@pedronasser can this one be closed?  I think this works now.
