### ISSUE TITLE
Setting configurations do not seem to take effect

### ISSUE THREAD

**Issue by nii236** [iron-io/functions#464]
I've been trying for awhile to get a database setup with my iron functions. No dice so far.

func.yaml env vars didn't seem to take effect so I tried setting it in the apps config:

```
$ fn apps config set myapp key value
myapp updated key with value

$ fn apps config view myapp
this application has no configurations
```

Is there something I need to setup before this works?

**Comment by nii236** [comment]
Creating an environment variable at app creation works:
```
$ fn apps create --config DB_URL=http://example.org/ myapp
```

```
$ fn apps config view myapp
myapp configuration:
DB_URL: http://example.org/
```

But when I actually want to access the app configuration it only appears as `_DB_URL`, not `DB_URL`.

**Comment by treeder** [comment]
@pedronasser do your new changes fix this?

**Comment by pedronasser** [comment]
This issue is solved.
I've just checked using the latest master.
