### ISSUE TITLE
What is the best way to secure the IronFunctions API?

### ISSUE THREAD

**Issue by cruxnet** [iron-io/functions#486]
I have been looking through the docs and haven't seen anything about how to secure access to the IronFunctions API. Is the expectation that IronFunctions will always be behind an HTTP Server and secured at that layer? Or are there plans to implement a security model?

**Comment by cruxnet** [comment]
I am considering using Iron Functions as the basis for an internal corporate FaaS. So I could put Nginx in front of the API but that would not give me fine grain control over creating, modifying, and deleting applications and routes. I know I can front fn with a web application that will manage access to the API but am wondering if that is something being considered as a feature in a future release so that using Iron Functions inside an enterprise is a turn key solution.

**Comment by treeder** [comment]
Hi @cruxnet , yes, we'll definitely be providing ways to add authentication/rights management in a future release. By next release (beta 2), we'll have the middleware and listeners all fleshed that will enable plugging in auth providers and what not. You can see that branch here and see how to use it: https://github.com/iron-io/functions/pull/474

We're using that to implement authentication in our internal Iron.io cluster. 

Feedback welcome.

**Comment by cruxnet** [comment]
What you describe is what I was looking for. Much appreciated. Thanks!

**Comment by zephinzer** [comment]
any updates on this? i can't seem to find relevant documentation on how to do this

**Comment by c0ze** [comment]
@zephinzer 

Yes, with `0.2.70` release, we introduced [Authentication via JWT tokens](https://github.com/iron-io/functions/blob/4656100582c3f5461afc9b28a7a1ce7b0b2cf465/docs/authentication.md). This uses the middleware approach treeder mentioned above. If you would like to use another scheme, that is also possible.

Please check it out and let us know your thoughts !
