### ISSUE TITLE
Postgres Example

### ISSUE THREAD

**Issue by jmank88** [iron-io/functions#489]
Is there interest in including a postgres example?  I created one analogous to the redis example (performs INSERT or SELECT) as an exercise, and it is essentially ready for PR.

**Comment by nii236** [comment]
Yes please! I tried doing it myself but kept hitting blockers with regards to app configuration as seen at #464

**Comment by jmank88** [comment]
I put up #490. I haven't tested enough yet, but in theory I didn't do anything new from the redis example that I initially cloned.
