### ISSUE TITLE
fn run doesn't pass env value literals

### ISSUE THREAD

**Issue by jmank88** [iron-io/functions#494]
See: https://github.com/iron-io/functions/blob/master/fn/run.go#L86

Notice that kv[1] is never used.  This means that something like 'fn run -e ENV_VAR' works fine, but a literal value like 'fn run -e ENV_VAR=VALUE' will be ignored, and behave the same as the former.

I'm guessing the expected behavior is to check for a value, and fall back to looking up the value if none is provided.

**Comment by treeder** [comment]
Per https://github.com/iron-io/functions/pull/490#discussion_r97586942, were you going to provide a fix @jmank88 ?

**Comment by jmank88** [comment]
Yes, I'll have a fix up soon.
