### ISSUE TITLE
Getting started issue

### ISSUE THREAD

**Issue by jakepearson** [iron-io/functions#500]
I am following the steps in the `quickstart`. I've gotten stuck on:

```
fn routes create myapp /hello
```

I get: `unexpected error: Post http:///v1/apps/myapp/routes: http: no Host in request URL`

Am I missing an environment variable?

**Comment by treeder** [comment]
Hi @jakepearson noticed you closed this, did you figure out the issue?

**Comment by jakepearson** [comment]
I did. Last night, it failed this morning, it all worked. I'm guessing it might be related to opening a new shell. Thanks for getting back to me.
