### ISSUE TITLE
QuickStart guide instructions for downloading fn don't work.

### ISSUE THREAD

**Issue by jconning** [iron-io/functions#501]
The Quickstart guide in functions/README.md says to install fn with "curl -sSL http://get.iron.io/fn | sh".  This doesn't work on my MacBook Pro running OS X Yosemite 10.10.5 because curl doesn't follow redirects by default.  But add the -L option and it works: "curl -L http://get.iron.io/fun | sh".

**Comment by treeder** [comment]
The README has the -L option already in `-sSL` so it should have already worked if that was the issue. 

`curl -sSL http://get.iron.io/fn | sh`

**Comment by derks** [comment]
Tested on latest macOS Sierra, and the original command `curl -sSL ...` **does** work just fine.  Not sure if that is an issue with cURL on Yosemite specifically... maybe providing output of the failing command might help?

**Comment by jconning** [comment]
I got confused and thought that `-sSL` was supposed to be `--ssl`.  Seriously I saw "sSL" and immediately thought SSL, secure sockets layer.  It didn't occur to me that it was actually `-s -S -L`.

False bug report!  But my eyes would be more pleased if it were `-s -S -L` or `-LSs`.

@treeder @derks
