### ISSUE TITLE
Docker and curl commands in functions/README.md don't work.

### ISSUE THREAD

**Issue by jconning** [iron-io/functions#512]
~~`curl get.iron.io/fn` needs a -L so it can follow the redirect.~~
`${pwd}` in docker run should actually be `${PWD}`.

Fix the README.md so that these commands work out of the box.

**Comment by treeder** [comment]
The fn part of this is a dupe of #501 .

**Comment by jconning** [comment]
These are both valid curl commands that do different things:
`curl -sSL`
`curl --ssl`

Maybe I'm the only nutcase who would ever be confused by this but what the heck I changed it to be `curl -LSs`.
