### ISSUE TITLE
How to add a route to an app with a local image?

### ISSUE THREAD

**Issue by tianluoqi** [iron-io/functions#514]
I want to add a route to an app with a local image which is not pushed to hub.docker.com or is pushed to a private registry like "registry.private.com". I can't find a way to configure the registry path and it always add "registry.hub.docker.com" in front of the image name.

**Comment by denismakogon** [comment]
@tianluoqi here are some related issues to your topic:
https://github.com/iron-io/functions/issues/506
https://github.com/iron-io/functions/issues/348
