### ISSUE TITLE
Quickstart - need changes to run on Mac - unexpected error: Post http://localhost:8080/v1/apps: dial tcp [::1]:8080: getsockopt: connection refused

### ISSUE THREAD

**Issue by divyavanmahajan** [iron-io/functions#515]
## Environment: MacPro running VirtualBox and Kitematic.

When you run `fn apps create myapp` - you get the error
`unexpected error: Post http://localhost:8080/v1/apps: dial tcp [::1]:8080: getsockopt: connection refused`

## Fix 
Before the `fn apps create myapp`, you must
`export API_URL="http://192.168.99.101:8080/"`

## Explanation:
The `fn` command by default looks for the API at `http://localhost:8080/`.
When you run the quickstart on your Mac, the docker port is mapped to 192.168.99.100 (which is the IP address of your Linux VirtualBox running Docker). So the ironfunctions docker container is accessible from 192.168.99.101 instead of localhost.

**Comment by treeder** [comment]
Ya, we've been assuming people will be using Docker for Mac going forward - https://docs.docker.com/docker-for-mac/ - which handles localhost properly. Perhaps we need a troubleshooting page with all the little gotchas.
