### ISSUE TITLE
fn build not working for python

### ISSUE THREAD

**Issue by jconning** [iron-io/functions#518]
Create the file func.py with a single line in it:
```print("Hello")```
Create the func.yaml file:
```fn init $USERNAME/hello```
Build the function:
```fn build```
Result:
```
Running prebuild command: docker run --rm -v /home/ubuntu/test:/worker -w /worker iron/python:2-dev pip install -t packages -r requirements.txt
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
You are using pip version 8.0.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
error running docker build: exit status 1
```
This was on Ubuntu 16.04.2 LTS (xenial).

**Comment by seiflotfy** [comment]
@jconning can you try updating ```pip install --upgrade pip```

**Comment by seiflotfy** [comment]
wait you need to add a requirements.txt by hand
in the same folder as the one with func.py

**Comment by jconning** [comment]
Seems like a bug to me.  Following the instructions in hello/python/README.md doesn't work.
https://github.com/iron-io/functions/tree/master/examples/hello/python/README.md

Don't we want the examples to work, as documented, so new people have a good experience?

**Comment by seiflotfy** [comment]
Fixing it

**Comment by jconning** [comment]
Gotcha

**Comment by treeder** [comment]
Need to somehow test the docs or something. We're not updating docs along with code very well.
