### ISSUE TITLE
error: routes creation takes at least three arguments: app name, route path and image name

### ISSUE THREAD

**Issue by narg95** [iron-io/functions#539]
When I execute `fn routes create myapp /hello` following the steps and example from the README file it fails with the message: *error: routes creation takes at least three arguments: app name, route path and image name*

## Docker version:
```sh
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

## Workaround
- Execute `docker ps` check for the image name and *TAG* and run `fn routes create myapp /hello $USER/hello:$TAG`. For example `fn routes create myapp /hello nesterran/hello:0.0.1`

**Comment by treeder** [comment]
Oh, looks like we need to merge a PR: https://github.com/iron-io/functions/pull/526

Once that's in, this should be fixed.

**Comment by narg95** [comment]
Great !
