### ISSUE TITLE
If image doesn't exist, no error is returned to user

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#540]
If image is not found in the registry at run time, the user gets a blank 200 response. It should return an error, 404 or something.

**Comment by seiflotfy** [comment]
the merged code changed the return to 401
```ERRO[0003] Credentials not authorized, trying next.      error="Get https://registry.hub.docker.com/v2/iron/notexist/manifests/latest: http: non-successful response (status=401 body=\"{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"iron/notexist","Action":"pull"}]}]}")" image="iron/notexist" server= username=```

**Comment by Gouthamve** [comment]
Umm, I think the error should be 500. Because the docker client is probably not authorised and not the client making the request.

**Comment by seiflotfy** [comment]
I think it should be 404 since the image does NOT EXIST

**Comment by Gouthamve** [comment]
Umm, the route exists (its mapped to an image and is registered). But the server internally is not able to run the image and errors out.

404 is for routes that are not even registered. But again, this is just minor and I guess we can go with 404 also for now.

**Comment by seiflotfy** [comment]
```fn routes create myapp /notexist iron/notexist``` the image does not exist
the path is not listed under `myapp`

**Comment by seiflotfy** [comment]
@Gouthamve I agree it should return 500, the path is registered so 404 is not ideal

**Comment by seiflotfy** [comment]
@Gouthamve WDYT?

**Comment by Gouthamve** [comment]
Yep! This sounds good!

**Comment by treeder** [comment]
Hmmm, that sounds right, 5XX of some sort is probably most appropriate.
