### ISSUE TITLE
Hot function inactivity timeout

### ISSUE THREAD

**Issue by WTFKr0** [iron-io/functions#554]
Hi
What do you think about making the 30 seconds inactivity timeout a parameter for hot functions (http mode) ?
I can think about a function with high overhead in loading or database connection
If this function is called every 2 min from 8am to 9am for example, I think it would be great to tune the timeout efficiently
WDYT ?

**Comment by pedronasser** [comment]
@WTFKr0, when you say parameter do you mean a route configuration?

I agree in making the hot functions timeout configurable.

**Comment by WTFKr0** [comment]
Yep route configuration

**Comment by denismakogon** [comment]
@WTFKr0 I assume there's only one way to define timeout:

- extend HTTP Post to `/{app}/routes` to include new parameter (let's say, `inactivity_timeout`), but make it optional (similar to other optional parameter we maintain right now)

Would that make sense @pedronasser @seiflotfy @treeder ?
