### ISSUE TITLE
Documentation for func.yaml

### ISSUE THREAD

**Issue by adelevie** [iron-io/functions#557]
Is this something I write myself or is it always generated by `fn`?

What are the required and optional fields? I'm assuming the answer to this will help me debug this error:

```sh
$ fn routes create myapp /hello
error: function image name is missing
$ ls 
func.yaml hello.go
$ cat func.yaml 
name: adelevie/hellogo
version: 0.0.1
runtime: go
entrypoint: ./func
$ cat hello.go
package main

import (
    "encoding/json"
    "fmt"
    "os"
)

type Person struct {
    Name string
}

func main() {
    p := &Person{Name: "World"}
    json.NewDecoder(os.Stdin).Decode(p)
    fmt.Printf("Hello %v!", p.Name)
}
```

**Comment by treeder** [comment]
I think someone must have been broken in some recent commits. That should work and I just verified and got the same error. 

cc @pedronasser @seiflotfy

**Comment by pedronasser** [comment]
I'm actually working on that fix at this moment.

**Comment by seiflotfy** [comment]
I don't see whats broken....
```fn routes create myapp /hello iron/go```
the image is missing and it has to be accessible via docker or locally

**Comment by treeder** [comment]
@seiflotfy it used to read the image name from func.yaml, now it doesn't seem to work.

**Comment by treeder** [comment]
Should be fixed now, get latest cli and try again.
