### ISSUE TITLE
make docker-test still has a golang host dependency 

### ISSUE THREAD

**Issue by adelevie** [iron-io/functions#559]
`make docker-test` still has a golang host dependency.

I know https://github.com/iron-io/functions/pull/545 closed https://github.com/iron-io/functions/issues/544, but this is still a blocker for pure docker-based development. 

I believe the offending line is `-v $(shell go list ./... | grep -v vendor | grep -v examples | grep -v tool | grep -v fn | grep -v datastore)`, specifically `go list`.

**Comment by treeder** [comment]
Could we change that line to use a Go image, eg: `docker run ..... go:alpine sh -c 'go list ./... | grep -v vendor | grep -v examples | grep -v tool | grep -v fn | grep -v datastore'` ?

**Comment by adelevie** [comment]
I'd be happy to take a stab at this at some point. I'm newish to golang though. What does `go list` do in this context? e.g. why do we need this volume?

**Comment by adelevie** [comment]
I also just noticed the `test` folder is empty. Could there be more documentation as to how tests work here?
