### ISSUE TITLE
Env var REQUEST_URL contains only the path and query string, not the host and port.

### ISSUE THREAD

**Issue by jconning** [iron-io/functions#568]
The env var REQUEST_URL is available for the function to read.  According to the documentation, it should contain "the full URL for the request".
https://github.com/iron-io/functions/blob/master/docs/writing.md#inputs

Slack mention: https://open-iron.slack.com/archives/general/p1488563548000962

I suspect that the reason why it is not available is because gin.Context.Request.URL doesn't contain the host and port.  From the docs, "For most requests, fields other than Path and RawQuery will be empty. (See RFC 2616, Section 5.1.2)".
https://golang.org/pkg/net/http/#Request

A practical way to compose the full URL would be to read the host and port from the "Host" http header and prepend them to the path and query.

**Comment by denismakogon** [comment]
I guess, this issue will no longer be critical once we'd have fix for #567 merged, right @jconning ?

**Comment by jconning** [comment]
@denismakogon Yes that's right but the docs say that REQUEST_URL should contain the FULL url and @treeder indicated that it should.

**Comment by denismakogon** [comment]
@jconning ok, will submit PR soon.

**Comment by denismakogon** [comment]
@jconning see #580

**Comment by treeder** [comment]
@jconning can you verify this is fixed now?  re: #580

**Comment by denismakogon** [comment]
Closed via #580
