### ISSUE TITLE
FN CLI for build/push/bump do not allow zero arguments

### ISSUE THREAD

**Issue by mikeball** [iron-io/functions#569]
While following the quick start (with v0.2.33) and attempting to build a function as per example
```
# build the function
fn build
```
Results in 
```
ERROR: Missing required arguments: 
```

Best I can tell(but not sure) from source code is that the `cli build`, `fn push` and `fn bump` don't intend to require an argument.

A work around is to enter a dummy argument, which does not seem to be used and command passes validation and completes normally.

```
fn build abc123
```

**Comment by treeder** [comment]
@mikeball can you test latest after #572 fix?

**Comment by mikeball** [comment]
Tested and all works as expected.
