### ISSUE TITLE
Dind overlay old kernels

### ISSUE THREAD

**Issue by WTFKr0** [iron-io/functions#585]
There is an option to run docker on overlay2 on old kernels (like RHEL)
```overlay2.override_kernel_check```
See https://docs.docker.com/engine/reference/commandline/dockerd/#storage-driver-options  
  
Is that possible to add an option/env to iron/functions to handle that ?
From entrypoint, I can see :
```
set -ex
# modified from: https://github.com/docker-library/docker/blob/866c3fbd87e8eeed524fdf19ba2d63288ad49cd2/1.11/dind/dockerd-entrypoint.sh
# this will run either overlay or aufs as the docker fs driver, if the OS has both, overlay is preferred.
# rewrite overlay to use overlay2 (docker 1.12, linux >=4.x required), see https://docs.docker.com/engine/userguide/storagedriver/selectadriver/#overlay-vs-overlay2

fsdriver=$(grep -Eh -w -m1 "overlay|aufs" /proc/filesystems | cut -f2)

if [ $fsdriver == "overlay" ]; then
  fsdriver="overlay2"
fi

cmd="dockerd \
                --host=unix:///var/run/docker.sock \
                --host=tcp://0.0.0.0:2375 \
                --storage-driver=$fsdriver"
```

**Comment by denismakogon** [comment]
@WTFKr0 I assume you're talking about all-in-one installation of IronFunction + Docker (Docker-in-Docker use case), right? I'd think about mounting volume to an image will config files with desired options configured as you like. Would that be the case for you?

**Comment by WTFKr0** [comment]
I use the iron/functions:latest image
Before, it was working good without dind mode (I bind moutn the docker sock of host)
But in latest, function tried to launch dind even with the bind mount.
So I tried the dind mode, but fall into this issue

**Comment by WTFKr0** [comment]
OK I solve my problem with non dind mode (mounting docker socket)
The problem was I run the service in mode global
