### ISSUE TITLE
Make datastore tests work with remote Docker containers

### ISSUE THREAD

**Issue by denismakogon** [iron-io/functions#586]
While testing MySQL patch #575 i've noticed that all DB tests are expecting to have Docker that runs on localhost, so all containers are available on localhost via port forwarding.

So, this might be fine for things like CI, but think of Docker that runs on remote machine, and all containers are pinned to `0.0.0.0:<port>` by default.

In order to implement it, it is necessary to use:
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' iron-<datastore>-test
```
command to retrieve container IP address

**Comment by treeder** [comment]
Should just be able to connect to the remote host on whatever port the container is bound to  regardless of what IP the container has on the host.

**Comment by treeder** [comment]
Do tests really need to test against a remote datastore?

**Comment by jmank88** [comment]
I'm curious how the benchmarks from #523 would perform against real DB instances, so remote datastores make some sense in that case.  Can the tests can just be rigged to check `DB_URL`?

**Comment by denismakogon** [comment]
@treeder maybe i wasn't clear with explanation. Current datastore tests are failing for me because i don't have Docker running locally and all containers that tests are creating are bound to remote Docker host.
So, tests are expecting that Docker and its containers are accessible via localhost, see [1](https://github.com/iron-io/functions/blob/master/api/datastore/postgres/postgres_test.go#L15), [2](https://github.com/iron-io/functions/blob/master/api/datastore/postgres/postgres_test.go#L24), [3](https://github.com/iron-io/functions/blob/master/api/datastore/redis/redis_test.go#L16).

In order to make tests pass it is necessary to pull out container IP address once container is up and running to form connection string instead of expecting to have containers running on localhost/127.0.0.1
