### ISSUE TITLE
Setting route 'config' or 'headers' to null does not work

### ISSUE THREAD

**Issue by mazamats** [iron-io/functions#592]
NOTE: I'm still able to add vars, just can't remove/change them.

Example:

`curl -X PATCH --header 'Content-Type: application/json' --header 'Accept: application/json' -d '{"route":{"config":null}}' 'http://10.0.0.10:8080/v1/apps/myapp/routes/hello'`

This is the response, As you can see, `config` still has ` "format": "http"` in it.

```
{
  "message": "Route successfully updated",
  "route": {
    "app_name": "myapp",
    "path": "\/hello",
    "image": "azamatms\/hot2:0.0.1",
    "memory": 128,
    "headers": {
      
    },
    "type": "sync",
    "format": "http",
    "max_concurrency": 1,
    "timeout": 6,
    "config": {
      "format": "http"
    }
  }
}
```

**Comment by jmank88** [comment]
Can you try passing the keys you want to clear with null or empty values? `"config": {"format": ""}`

**Comment by mazamats** [comment]
@jmank88 That works for the `config`, I can change the value and delete it if its clear. However, it doesn't work for the `headers`

In fact, if I try to update a header to a new value, it will just append it to an array

**Comment by jmank88** [comment]
Headers are multi-value, so they are a bit un-intuitive to patch.  Did you try passing a null or empty array for the header key? That should delete all values for a key. `"headers": { "key": []}`

**Comment by mazamats** [comment]
Nice, that seemed to work too.

I guess this is mainly an issue with the Functions-UI, I was copying the API data it sent.
