### ISSUE TITLE
How Can I build from source code?

### ISSUE THREAD

**Issue by cmdhema** [iron-io/functions#593]
I try to follow getting start but I got below error
 "unexpected error: Get http://127.0.0.1:8080/v1/apps: dial tcp localhost:8080: getsockopt: connection refused" 
when I 'fn apps create myapp'

I checked process and I can't find using localhost:8080 process. 
So I try to build from source.
I install go(1.7.4) and glide. After then 'go install funstions' but I got below error 
'# github.com/iron-io/runner/drivers/docker
../github.com/iron-io/runner/drivers/docker/docker.go:141: cannot use mani (type *"github.com/heroku/docker-registry-client/vendor/github.com/docker/distribution/manifest/schema1".SignedManifest) as type *"github.com/docker/distribution/manifest/schema1".SignedManifest in field value
../github.com/iron-io/runner/drivers/docker/docker.go:159: cannot use r.Digest (type "github.com/docker/distribution/vendor/github.com/opencontainers/go-digest".Digest) as type "github.com/heroku/docker-registry-client/vendor/github.com/docker/distribution/digest".Digest in argument to s.reg.LayerMetadata
'
My environment is ubuntu 14.04, Docker 17.03

Thank you

**Comment by pedronasser** [comment]
To build it from the source you can just execute:
```
make dep
make build
```

**Comment by denismakogon** [comment]
@cmdhema recent master branch requires Go 1.8, so install it first and then use following commands:
`mkdir -p ~/go/src/github.com/iron-io`
`git clone https://github.com/iron-io/functions.git ~/go/src/github.com/iron-io/functions`
`export GOPATH=~/go`
`cd ~/go/src/github.com/iron-io/functions`
`make dep build`

Then you'll be able to find executable `functions`. See [docs](https://github.com/iron-io/functions/blob/master/docs/options.md) for further configuration.
Then you can start API service using following command:
`make run`

**Comment by cmdhema** [comment]
I use glide 0.12.3
go 1.8.1
ubuntu 14.04 lts
Master branch irconfunctions

Thank you for your reply @pedronasser @denismakogon 

After 'make dep build' I got some info messages, below examples 
...
[INFO]	--> Found desired version locally github.com/amir/raidman c74861fe6a7bb8ede0a010ce4485bdbb4fc4c985!
[INFO]	--> Found desired version locally github.com/asaskevich/govalidator 7b3beb6df3c42abd3509abfc3bcacc0fbfb7c877!
[INFO]	--> Found desired version locally github.com/aws/aws-sdk-go 90dec2183a5f5458ee79cbaf4b8e9ab910bc81a6!
....

But I got below errors
[INFO]	--> Found desired version locally github.com/urfave/cli 0bdeddeeb0f650497d603c4ad7b20cfe685682f6!
[INFO]	--> Fetching golang.org/x/crypto.
[INFO]	--> Fetching gopkg.in/go-playground/validator.v8.
[INFO]	--> Fetching golang.org/x/sys.
[INFO]	--> Fetching golang.org/x/text.
[INFO]	--> Fetching gopkg.in/mgo.v2.
[INFO]	--> Fetching gopkg.in/yaml.v2.
[INFO]	--> Fetching golang.org/x/net.
[WARN]	Unable to checkout golang.org/x/crypto
[ERROR]	Update failed for golang.org/x/crypto: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/net
[ERROR]	Update failed for golang.org/x/net: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/text
[ERROR]	Update failed for golang.org/x/text: Cannot detect VCS
[WARN]	Unable to checkout golang.org/x/sys
[ERROR]	Update failed for golang.org/x/sys: Cannot detect VCS
[WARN]	Unable to checkout gopkg.in/yaml.v2
[ERROR]	Update failed for gopkg.in/yaml.v2: Cannot detect VCS
[WARN]	Unable to checkout gopkg.in/mgo.v2
[ERROR]	Update failed for gopkg.in/mgo.v2: Cannot detect VCS
[WARN]	Unable to checkout gopkg.in/go-playground/validator.v8
[ERROR]	Update failed for gopkg.in/go-playground/validator.v8: Cannot detect VCS
[ERROR]	Failed to install: Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
Cannot detect VCS
make: *** [dep] Error 1

How can I download golang.org/x/crypto, x/net...... ?
I have several attempts to do this, but failed.

Thanks

**Comment by jmank88** [comment]
`Cannot detect VCS` sounds like it cannot find `git`
Are you able to run `go get golang.org/x/crypto`?

**Comment by cmdhema** [comment]
I solved my another machine. Thankyou
