### ISSUE TITLE
Error: pq: relation "apps" does not exist

### ISSUE THREAD

**Issue by wjimenez5271** [iron-io/functions#613]
Function worker throws this error: 
```
Error: pq: relation "apps" does not exist
```

In the postgres DB I see

```
3/28/2017 12:14:14 PMERROR:  relation "apps" does not exist at character 24
3/28/2017 12:14:14 PMSTATEMENT:  SELECT DISTINCT * FROM apps
```

**Comment by jmank88** [comment]
Was it working previously?
`CREATE TABLE IF NOT EXISTS apps...` should be executed each time the Datastore code connects, so a restart might get it going again.

**Comment by wjimenez5271** [comment]
@jmank88 yep, a restart fixed it.

**Comment by wjimenez5271** [comment]
Hmm, now after creating a new app
```
$ fn apps create myapp
myapp created
```

I get

```
Error: unexpected end of JSON input
```

**Comment by pedronasser** [comment]
Fixed in the latest release.
