### ISSUE TITLE
passing data into an asynchronous function

### ISSUE THREAD

**Issue by Tofull** [iron-io/functions#628]
Hi,

I am very interested in asynchronous functions as I am working on deep learning for image processing.

IronFunctions seems to not pass data when the functions are type: async.
In the [async section of the readme](https://github.com/iron-io/functions/blob/master/README.md#add-an-asynchronous-function), the route is requested with `{
    "name":"Johnny"
}` data and the queued function returns `Hello World!` instead of `Hello Johnny!` as sync-version does the stuff.

This issue first appeared to me when I was trying an asynchronous hello world in python, taking a json file as the [sync-version of python hello world](https://github.com/iron-io/functions/blob/master/examples/hello/python/hello.py) does and the queued function returns: 
> INFO[9116] Pushed to MQ
> INFO[9116] Added new task to queue
> INFO[9116] Reserved
> INFO[9116] 
> INFO[9116] 
> INFO[9116] Deleted
> INFO[9116] Task complete
> INFO[9116] Traceback (most recent call last):
> INFO[9116]   File "hello.py", line 9, in <module>
> INFO[9116]     obj = json.loads(sys.stdin.read())
> INFO[9116]   File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
> INFO[9116]     return _default_decoder.decode(s)
> INFO[9116]   File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
> INFO[9116]     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> INFO[9116]   File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
> INFO[9116]     raise ValueError("No JSON object could be decoded")
> INFO[9116] ValueError: No JSON object could be decoded
> INFO[9116] container status

Thanks

**Comment by c0ze** [comment]
@Tofull we have a new release 0.2.65 which should fix this issue ! Please let us know if you could confirm this !
