### ISSUE TITLE
Docker temporary error

### ISSUE THREAD

**Issue by JJ** [iron-io/functions#643]
I get this message when trying to run the example. This is ubuntu 14.04, Docker version 17.05.0-ce, build 89658be
```
ARN[0292] docker temporary error, retrying              error="API error (500): {"message":"oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:291: setting cgroup config for ready process caused \\\"failed to write 0 to memory.swappiness: write /sys/fs/cgroup/memory/docker/550a8155b5ba202f05f440d750903b52c943ae3f7145172e5a9c53cb029bc27b/memory.swappiness: invalid argument\\\"\"\n"}
```
This is repeated several times, actually... I'm using a local docker, and prefixing orders with sudo, which is my default installation.

**Comment by JJ** [comment]
Seems to be a problem with Ubuntu 14.04 https://github.com/opencontainers/runc/issues/16

**Comment by c0ze** [comment]
Hello there,

I'm not sure this is a problem about iron functions. My advice would be to update your installation (14.04 is getting old) and preferably update your setup so that you don't need to use sudo.
