### ISSUE TITLE
Unable to get API URL working with SSL termination through load balancers

### ISSUE THREAD

**Issue by wrsuarez** [iron-io/functions#649]
We've got a CNAME to our ingress load balancer in Rancher for Iron Functions. Running a valid wildcard SSL through from the ingress LB for the environment, SNI to the Stack LB, termination of SSL at the stack load balancer then redirection of traffic from 443 to 8080 in the Function Workers containers. Same set up for the UI. On the UI side everything works perfectly fine. No specification of port 4000 is required. On the API said I get an error when trying to do the same thing:

MASKED:demoapp rsuarez$ fn apps create testapp2
unexpected error: no consumer: "text/html"

<img width="243" alt="screen shot 2017-09-27 at 9 09 12 am" src="https://user-images.githubusercontent.com/5407533/30924740-80cae114-a364-11e7-95fc-374ae32d1a06.png">

**Comment by wrsuarez** [comment]
I should add that setting the export for the API URL on my laptop to anything but 8080 doesn't work. Using https, http with port 80, all result in the same error

**Comment by c0ze** [comment]
thank you for the report ! This is an issue we are working on, hopefully it will be resolved soon !

https://github.com/iron-io/functions/pull/650

**Comment by c0ze** [comment]
@wrsuarez we just released a new version of the fn tool which should solve this issue. Please give it a try and let us know if this works for you ! Thanks !

**Comment by wrsuarez** [comment]
@coze I'll check it out right now

**Comment by wrsuarez** [comment]
@c0ze call this one closed. Thank you! 👍
