### ISSUE TITLE
Scaling

### ISSUE THREAD

**Issue by reiz** [iron-io/functions#656]
I followed the instructions in the README and it worked perfectly on my local machine. Just wondering how to scale this. How can I use this on cluster of 20 machines. On Docker swarm or K8S? The documentation doesn't tell anything about this.

**Comment by c0ze** [comment]
Thanks for the feedback ! Glad that it worked for you ! 👍 

Here are a few pointers to get you started :

http://blog.lwolf.org/post/how-to-run-functions-in-your-kubernetes-cluster/
https://github.com/iron-io/functions/tree/master/docs/operating
https://github.com/kunihiko-t/jwt-example

Sorry some of these resources are somewhat outdated, so may need some tuning. Running on K8s or Docker Swarm is definitely on the roadmap, so we will go over these and update the docs soon ! Stay tuned ! (If you notice any issues with the documentation, you are more than welcome to contribute too !)

**Comment by reiz** [comment]
@c0ze Many thanks! That helps me a lot.
