### ISSUE TITLE
Can fn command run locally? 

### ISSUE THREAD

**Issue by sss0350** [iron-io/functions#665]
Hello there, just want to very impress by iron-function features. 
We are trying to adopt in enterprise environment with network protection. (can only access intranet)
I've successfully running basic function & function-ui functionality on our linux (centOS). 
But I encounter some issues while using fn command, I'm using following fn binary.
https://github.com/iron-io/functions/releases/download/0.2.71/fn_linux
It seems some command needs internet access to complete? 
I'll give 2 samples of my failure command. Please help give me some solutions , I want to know if there's any way to pre-download some images or file command line need beforehand? Please kindly told me what to download and where to put it.

a) fn apps list
unexpected error: [GET /apps][404] GetApps default  &{Error:<nil>}

b)  fn routes list myapps
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9999ff]

goroutine 1 [running]:
github.com/iron-io/functions/fn/commands.(*routesCmd).list(0xc42008a0b8, 0xc4200e7b80, 0x1, 0xae8f14)
/home/ubuntu/go/src/github.com/iron-io/functions/fn/commands/routes.go:185 +0x92f
github.com/iron-io/functions/fn/commands.(*routesCmd).(github.com/iron-io/functions/fn/commands.list)-fm(0xc4200e7b80, 0x0, 0xc420444e50)
/home/ubuntu/go/src/github.com/iron-io/functions/fn/commands/routes.go:91 +0x34
github.com/iron-io/functions/vendor/github.com/urfave/cli.HandleAction(0xa180e0, 0xc420444830, 0xc4200e7b80, 0x1, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/iron-io/functions/fn/app.prepareCmdArgsValidation.func1(0xc4200e7b80, 0x0, 0xc4200e7b80)
/home/ubuntu/go/src/github.com/iron-io/functions/fn/app/app.go:120 +0x357
github.com/iron-io/functions/vendor/github.com/urfave/cli.HandleAction(0xa180e0, 0xc420451120, 0xc4200e7b80, 0xc420069200, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.Run(0xae89f2, 0x4, 0x0, 0x0, 0xc4204448b0, 0x1, 0x1, 0xaf8bc5, 0x15, 0x0, ...)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/iron-io/functions/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc4203aa4e0, 0xc4200e7900, 0x0, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.startApp(0xaeaf5b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf1f2e, 0xd, 0x0, ...)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:280 +0x824
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.Run(0xaeaf5b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf1f2e, 0xd, 0x0, ...)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:79 +0x14c7
github.com/iron-io/functions/vendor/github.com/urfave/cli.(*App).Run(0xc4203aa340, 0xc420082100, 0x4, 0x4, 0x0, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
/home/ubuntu/go/src/github.com/iron-io/functions/fn/main.go:10 +0x53
[root@a12slpaas04 data]# fn routes list myapp2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9999ff]

goroutine 1 [running]:
github.com/iron-io/functions/fn/commands.(*routesCmd).list(0xc42018c090, 0xc4200d7b80, 0x1, 0xae8f14)
/home/ubuntu/go/src/github.com/iron-io/functions/fn/commands/routes.go:185 +0x92f
github.com/iron-io/functions/fn/commands.(*routesCmd).(github.com/iron-io/functions/fn/commands.list)-fm(0xc4200d7b80, 0x0, 0xc420290800)
/home/ubuntu/go/src/github.com/iron-io/functions/fn/commands/routes.go:91 +0x34
github.com/iron-io/functions/vendor/github.com/urfave/cli.HandleAction(0xa180e0, 0xc420290140, 0xc4200d7b80, 0x1, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/iron-io/functions/fn/app.prepareCmdArgsValidation.func1(0xc4200d7b80, 0x0, 0xc4200d7b80)
/home/ubuntu/go/src/github.com/iron-io/functions/fn/app/app.go:120 +0x357
github.com/iron-io/functions/vendor/github.com/urfave/cli.HandleAction(0xa180e0, 0xc420436840, 0xc4200d7b80, 0xc420316e00, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.Run(0xae89f2, 0x4, 0x0, 0x0, 0xc4202901c0, 0x1, 0x1, 0xaf8bc5, 0x15, 0x0, ...)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:193 +0xb72
github.com/iron-io/functions/vendor/github.com/urfave/cli.(*App).RunAsSubcommand(0xc420062340, 0xc4200d7900, 0x0, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:374 +0xacc
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.startApp(0xaeaf5b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf1f2e, 0xd, 0x0, ...)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:280 +0x824
github.com/iron-io/functions/vendor/github.com/urfave/cli.Command.Run(0xaeaf5b, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xaf1f2e, 0xd, 0x0, ...)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/command.go:79 +0x14c7
github.com/iron-io/functions/vendor/github.com/urfave/cli.(*App).Run(0xc4203efd40, 0xc420010200, 0x4, 0x4, 0x0, 0x0)
/home/ubuntu/go/src/github.com/iron-io/functions/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
/home/ubuntu/go/src/github.com/iron-io/functions/fn/main.go:10 +0x53

**Comment by c0ze** [comment]
Hello,

Thank you for your interest in our platform !

`fn` tool itself shouldn't require internet connectivity. If the functions service is running on another machine, you need to supply `API_URL` env when making `fn` calls though. Please check :

https://github.com/iron-io/functions/blob/3c4261ae37accf6c51a6aee6b216f58c84621d6c/docs/operating/options.md#L16

like this :

```
API_URL=192.168.10.11:4000 fn apps list
```

hope this helps ! 👍

**Comment by sss0350** [comment]
Hello @c0ze,
Thanks for your quick reply!  At first, I'm getting some trouble to make it work. fn command still can't get API_URL from my environment variables. 
And then I find your release page , there's a bug fix about API_URL.... 3 days before.... 
And I download it, put it to /usr/local/bin , it works like a charm! 
I'll detail testing all other functions tmr , thank you!

**Comment by c0ze** [comment]
@sss0350 thanks for checking and the feedback ! Yes, in your initial message you linked to `0.2.71` so I thought you already had the latest version. I'm glad that updating fixed your issue !

Please let us know if you run into any other problems !
