### ISSUE TITLE
How to run on Openstack

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#67]

**Comment by treeder** [comment]
@derekschultz can we get this out now?  The murano package, the runbook and how about a blog post too?

**Comment by derekschultz** [comment]
Yep, just got the logo this morning. Will get that into the Murano app today and take necessary screenshots to add to runbook. I can have it ready to submit to OpenStack app catalog by tomorrow. Runbook may take another day or so. Blog post is a good idea.

**Comment by derekschultz** [comment]
IronFunctions Murano app pushed to app-catalog: https://review.openstack.org/#/c/407223/

Repo here, will make public unless anyone objects: https://github.com/iron-io/ironfunctions-murano

Closing issue.
