### ISSUE TITLE
Can't install on kubernetes

### ISSUE THREAD

**Issue by meysam001** [iron-io/functions#673]
Hello
I'm trying to install the iron on kubernetes. When I had ran 
```
git clone https://github.com/iron-io/functions
cd docs
kubectl create -f kubernetes-quick
```
I gave the an error: `error: the path "kubernetes-quick" does not exist`

What are Prequisites for installing `iron` on kubernetes?

**Comment by c0ze** [comment]
sorry, can you please change to `cd docs/operating` and try again ? It seems the documentation is outdated.

**Comment by meysam001** [comment]
@c0ze  thank you it worked.
