### ISSUE TITLE
can't create an app

### ISSUE THREAD

**Issue by meysam001** [iron-io/functions#674]
Hello
I'm trying to create an app. When I had ran `fn apps create myapp`, I gave `unexpected error: Post http://localhost:8080/v1/apps: dial tcp [::1]:8080: getsockopt: connection refused`

I tryid to port forwarding that but when I run the command `kubectl port-forward functions-65c64ddf68-ml9nz 8080`, it will show the output 
```
Forwarding from 127.0.0.1:8080 -> 8080

```
then it will stay in this status and won't happened until I press ctrl+c.

What is wrong?

**Comment by c0ze** [comment]
yes, it seems you need to run port forwarding running in the background. Please open a new tab, run `kubectl port-forward functions-65c64ddf68-ml9nz 8080` and let it run. Then in another panel, run `fn` command.

I'll check if it is possible to make port forwarded by default.

**Comment by meysam001** [comment]
I have run `kubectl port-forward functions-65c64ddf68-ml9nz 8080` agian, then I have wait for 30 minutes. But it was not happening.
![image](https://user-images.githubusercontent.com/30567013/37391544-c0357b16-2780-11e8-978f-627b7c23c2c8.png)

**Comment by c0ze** [comment]
ok. while you are doing this, did you try `fn` command ?

**Comment by meysam001** [comment]
I run again `fn` command  a few seconds before, the output was changed : 
![image](https://user-images.githubusercontent.com/30567013/37392861-a3d401d2-2784-11e8-8baf-7e73521fd7c9.png)

**Comment by c0ze** [comment]
ok, it seems it worked, now if you do `fn apps list` you should see your app listed.

**Comment by meysam001** [comment]
It worked! Thanks a lot @c0ze. You are great man :100:
