### ISSUE TITLE
unsupported runtime nodejs6.10

### ISSUE THREAD

**Issue by si458** [iron-io/functions#677]
Hi,
when im trying to import an existing lamba into functions i keep getting an error saying
`unsupported runtime nodejs6.10`
am i doing something wrong?
`SiMacBookPro:func Simon$ fn lambda aws-import arn:aws:lambda:us-east-1:1234567890:function:MySiteCheck-dev-hello us-east-1 myuser/mysitecheck`

**Comment by c0ze** [comment]
Hello there,

You are not doing anything wrong. It seems only `4.3` is supported atm.

https://github.com/iron-io/functions/blob/e1c0012d04897a0c204e0dafb3ede689cf445f83/fn/commands/lambda.go#L154

`6.10` seems to have been introduced last may.

https://aws.amazon.com/about-aws/whats-new/2017/03/aws-lambda-supports-node-js-6-10/

**Comment by si458** [comment]
is the anyway for you to update functions to support nodejs6.10? 
as its been around for a year now, 
and its sorta mainstream as 4.3 is now past its sell by date
