### ISSUE TITLE
how to secure operating api

### ISSUE THREAD

**Issue by imacks** [iron-io/functions#680]
its my first time trying this project. i must be missing something in the docs, but how to i secure app creation api? like, is there a concept of users here? set the number of apps a user can create? give a user some kind of api key to protect his app routes from unauthorized editing? do i need to rite jwt middleware for all that?

**Comment by c0ze** [comment]
Unfortunately, there is no concept of `users` or fine grained access control. You can secure global API by issuing JWT tokens, please check the [Authentication](https://github.com/iron-io/functions#authentication) docs for more information. For fine grain control, you can set route level JWT tokens, and distribute to your users maybe.

**Comment by imacks** [comment]
good to know. to have access control to /v1/apps (deploying and updating apps),  what kind of middleware will i need to write? is there a guide somewhere?

**Comment by c0ze** [comment]
You don't need to write any middleware. You just need to pass an ENV when starting the functions server. You also need to pass the same token when you are issuing commands via the `fn` tool (or accessing the API in any way). Please check the documentation I provided before. 

If you need to modify the implementation (write your own middleware etc), please check the following PRs, they may give you ideas. Thank you !

https://github.com/iron-io/functions/pull/662
https://github.com/iron-io/functions/pull/660

**Comment by imacks** [comment]
hmm i can't find the name of the env...help pls?

**Comment by imacks** [comment]
tks that certainly helps. I'll try to implement users then...
