### ISSUE TITLE
Function orchestator

### ISSUE THREAD

**Issue by apercova** [iron-io/functions#682]
Hi!
I've been playing with Iron Functions for a few days and I wonder if there is a function orchestating solution out of the box that I could use to coordinate operations between functions.

Thank's in advance.

**Comment by dylanz** [comment]
Hello!  You should be able to integrate directly into Docker Swarm or Kubernetes.  Some more information found here (the bottom of this page):  https://github.com/iron-io/functions/blob/master/docs/README.md
