### ISSUE TITLE
Long(er) running containers for better performance aka Hot Containers

### ISSUE THREAD

**Issue by treeder** [iron-io/functions#69]
Instead of one off execution, keep container running for a while and take requests.  

The first version executes a container per function call/request. Which is fine for many things, but we may want a way to run for longer periods of time to increase performance due to things like keeping db connections open, etc. 

This would probably require a more lambda like code format and language libraries. See https://github.com/iron-io/lambda for existing work on lambda style code format. 

I created a prototype of this years ago that routed traffic into IronWorker containers, should dig that out and look into that implementation.

**Comment by ccirello** [comment]
See #214

**Comment by ccirello** [comment]
https://github.com/iron-io/functions/pull/332 fixes this
