### ISSUE TITLE
Sounds promising but

### ISSUE THREAD

**Issue by Serhioromano** [iron-io/functions#715]
I must share my experience in hope of may be improvement in the future.

I've found this project in Portainer templates. I read about this and decided to test it. Maybe I am not a maestro, but I am 20 years developer. Installation through portainer templates does not work at all. Not true, API seams working. But not UI. I was so interested that I try to use instructions. After few attempts, I've found small note

> NOTE: latest version is broken, please use 0.0.2

Which is ridiculous, how I am supposed to see it if I do not read manuals, I just look at code or command examples and that is enough for me. If it is broke, fix it or rollback but it makes no sense to have broken app in a registry. 

Anyway, that gave me hope that I'll be able finally to use it. UI is the only reason I try. I do not want to send CURL requests, this will make development process cumbersome. I was able to run image and UI show up. But when I create new app it says `Error: An error ocurred.`. Really? Are you serious? Thank you very much that is so kind that you inform that some error oc**C**urred. 

Also, manuals are not very clear. It shows commands but were to run it? Inside docker container? Which one?

May be I'll try it after few months pass. May be not. But if you really want this to become a thing, no need for too many functionalities and sophisticated features. Just make initial experience smooth and let developer have something in few minutes.

**Comment by JokerQyou** [comment]
It's worth noticing that this project seems to be abandoned, no more updates since 2018.

**Comment by QWQyyy** [comment]
well notes
